import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useFieldArray, useForm, useWatch } from 'react-hook-form'
import { z } from 'zod'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useAppointmentsQuery } from '@/features/appointments/appointments.queries'
import { useCustomersQuery } from '@/features/customers/customers.queries'
import { useBranchesQuery, useEmployeesQuery } from '@/features/employees/employees.queries'
import { useServicesQuery } from '@/features/services/services.queries'
import { createSale, saleKeys } from './sales-api'
import { saleError } from './sales-error'
import type { CreateSaleInput, Sale } from './types'

const money = /^(?:0|[1-9]\d{0,9})(?:\.\d{1,2})?$/
const itemSchema = z.object({ serviceId: z.string(), type: z.enum(['SERVICE', 'PRODUCT', 'OTHER']), description: z.string().trim().min(1, 'Descripción obligatoria.'), quantity: z.coerce.number().int().min(1).max(10000), unitPrice: z.string().regex(money, 'Importe decimal no válido.') })
const schema = z.object({ mode: z.enum(['manual', 'appointment']), appointmentId: z.string(), branchId: z.string(), customerId: z.string(), employeeId: z.string(), items: z.array(itemSchema), discountTotal: z.string().regex(money), taxTotal: z.string().regex(money), notes: z.string().max(2000) }).superRefine((value, ctx) => {
  if (value.mode === 'appointment' && !z.string().uuid().safeParse(value.appointmentId).success) ctx.addIssue({ code: 'custom', path: ['appointmentId'], message: 'Selecciona una cita.' })
  if (value.mode === 'manual') { if (!z.string().uuid().safeParse(value.branchId).success) ctx.addIssue({ code: 'custom', path: ['branchId'], message: 'Selecciona una sucursal.' }); if (!value.items.length) ctx.addIssue({ code: 'custom', path: ['items'], message: 'Añade al menos un ítem.' }) }
})
type Values = z.infer<typeof schema>

export function SaleForm({ permissions, onClose, onSaved }: { permissions: string[]; onClose: () => void; onSaved: (sale: Sale) => void }) {
  const client = useQueryClient(), canAppointments = permissions.includes('appointments.view'), canCustomers = permissions.includes('customers.view'), canEmployees = permissions.includes('employees.view'), canServices = permissions.includes('services.view')
  const form = useForm<Values>({ defaultValues: { mode: 'manual', appointmentId: '', branchId: '', customerId: '', employeeId: '', items: [{ serviceId: '', type: 'OTHER', description: '', quantity: 1, unitPrice: '0.00' }], discountTotal: '0.00', taxTotal: '0.00', notes: '' } })
  const fields = useFieldArray({ control: form.control, name: 'items' }), mode = useWatch({ control: form.control, name: 'mode' }), watchedItems = useWatch({ control: form.control, name: 'items' })
  const [now] = useState(() => Date.now()), appointments = useAppointmentsQuery({ from: new Date(now - 15 * 86_400_000).toISOString(), to: new Date(now + 15 * 86_400_000).toISOString(), page: 1, pageSize: 100 }, canAppointments && mode === 'appointment')
  const branches = useBranchesQuery(canEmployees && mode === 'manual'), customers = useCustomersQuery({ search: '', page: 1, pageSize: 100 }, canCustomers && mode === 'manual'), employees = useEmployeesQuery({ search: '', page: 1, pageSize: 100 }, canEmployees && mode === 'manual'), services = useServicesQuery({ search: '', page: 1, pageSize: 100 }, canServices && mode === 'manual')
  const mutation = useMutation({ mutationFn: (values: Values) => { const input: CreateSaleInput = values.mode === 'appointment' ? { appointmentId: values.appointmentId, notes: values.notes.trim() } : { branchId: values.branchId, customerId: values.customerId || undefined, employeeId: values.employeeId || undefined, items: values.items.map((item) => ({ ...item, serviceId: item.serviceId || undefined, description: item.description.trim() })), discountTotal: values.discountTotal, taxTotal: values.taxTotal, notes: values.notes.trim() }; return createSale(input) }, onSuccess: async (sale) => { client.setQueryData(saleKeys.detail(sale.id), sale); await client.invalidateQueries({ queryKey: saleKeys.lists() }); onSaved(sale) } })
  const submit = form.handleSubmit(async (raw) => { const result = schema.safeParse(raw); if (!result.success) { for (const issue of result.error.issues) { const field = issue.path[0]; if (typeof field === 'string') form.setError(field as keyof Values, { message: issue.message }) } return } await mutation.mutateAsync(result.data).catch(() => undefined) })
  const chooseService = (index: number, id: string) => { const service = services.data?.items.find((item) => item.id === id); form.setValue(`items.${index}.serviceId`, id); if (service) { form.setValue(`items.${index}.type`, 'SERVICE'); form.setValue(`items.${index}.description`, service.name); form.setValue(`items.${index}.unitPrice`, service.price) } }
  const activeAppointments = appointments.data?.items.filter((item) => !['CANCELLED', 'RESCHEDULED'].includes(item.status)) ?? []
  return <form className="space-y-5" onSubmit={submit} noValidate>
    <div className="flex gap-2"><Button type="button" variant={mode === 'manual' ? 'default' : 'outline'} onClick={() => form.setValue('mode', 'manual')}>Venta manual</Button><Button type="button" variant={mode === 'appointment' ? 'default' : 'outline'} onClick={() => form.setValue('mode', 'appointment')}>Desde cita</Button></div>
    {mode === 'appointment' ? <Field label="Cita" error={form.formState.errors.appointmentId?.message}>{!canAppointments ? <p className="text-sm text-destructive">Necesitas appointments.view para seleccionar una cita.</p> : <select className={selectClass} {...form.register('appointmentId')}><option value="">Selecciona una cita activa</option>{activeAppointments.map((item) => <option key={item.id} value={item.id}>{new Date(item.startAt).toLocaleString()} · {item.customer.name} · {item.employee.displayName}</option>)}</select>}</Field> : <>
      {(!canEmployees || !canServices) && <p className="text-sm text-destructive">La venta manual requiere lectura de empleados/sucursales y servicios.</p>}
      <div className="grid gap-4 md:grid-cols-3"><Field label="Sucursal" error={form.formState.errors.branchId?.message}><select className={selectClass} {...form.register('branchId')}><option value="">Selecciona</option>{branches.data?.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Cliente"><select className={selectClass} disabled={!canCustomers} {...form.register('customerId')}><option value="">Sin cliente</option>{customers.data?.items.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Empleado"><select className={selectClass} {...form.register('employeeId')}><option value="">Sin empleado</option>{employees.data?.items.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></Field></div>
      <section className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-medium">Ítems</h3><Button type="button" size="sm" variant="outline" onClick={() => fields.append({ serviceId: '', type: 'OTHER', description: '', quantity: 1, unitPrice: '0.00' })}>Añadir ítem</Button></div>{fields.fields.map((field, index) => <div key={field.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-6"><select className={`${selectClass} md:col-span-2`} value={watchedItems[index]?.serviceId ?? ''} onChange={(event) => chooseService(index, event.target.value)}><option value="">Ítem libre</option>{services.data?.items.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input className="md:col-span-2" placeholder="Descripción" {...form.register(`items.${index}.description`)} /><Input type="number" min="1" aria-label="Cantidad" {...form.register(`items.${index}.quantity`)} /><Input inputMode="decimal" aria-label="Precio unitario" {...form.register(`items.${index}.unitPrice`)} /><div className="md:col-span-6"><Button type="button" size="sm" variant="outline" onClick={() => fields.remove(index)} disabled={fields.fields.length === 1}>Quitar</Button></div></div>)}{form.formState.errors.items?.message && <p className="text-xs text-destructive">{form.formState.errors.items.message}</p>}</section>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Descuento"><Input inputMode="decimal" {...form.register('discountTotal')} /></Field><Field label="Impuestos"><Input inputMode="decimal" {...form.register('taxTotal')} /></Field></div>
    </>}
    <Field label="Notas"><textarea className="min-h-20 w-full rounded-lg border border-input bg-transparent px-2.5 py-2 text-sm" {...form.register('notes')} /></Field>
    <div className="flex gap-2"><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Creando…' : 'Crear venta'}</Button><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button></div>{mutation.error && <p role="alert" className="text-sm text-destructive">{saleError(mutation.error)}</p>}
  </form>
}
const selectClass = 'h-9 w-full rounded-lg border border-input bg-transparent px-2.5 text-sm'
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="space-y-1.5 text-sm font-medium"><span>{label}</span>{children}{error && <span className="block text-xs text-destructive">{error}</span>}</label> }
