import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useSession } from '@/features/auth/use-session'
import { SaleDetail } from '@/features/sales/sale-detail'
import { statusLabel } from '@/features/sales/sale-status'
import { SaleForm } from '@/features/sales/sale-form'
import { saleError } from '@/features/sales/sales-error'
import { useSale, useSales } from '@/features/sales/use-sales'
import type { SaleStatus } from '@/features/sales/types'

const PAGE_SIZE = 20
export function SalesPage() {
  const { data: principal } = useSession(), permissions = principal?.actorType === 'USER' ? principal.permissions : [], canView = permissions.includes('sales.view'), canManage = permissions.includes('sales.manage')
  const [searchInput, setSearchInput] = useState(''), [search, setSearch] = useState(''), [status, setStatus] = useState<SaleStatus | ''>(''), [page, setPage] = useState(1), [creating, setCreating] = useState(false), [selectedId, setSelectedId] = useState('')
  const sales = useSales({ search, status, page, pageSize: PAGE_SIZE }, canView), detail = useSale(selectedId, canView && Boolean(selectedId))
  if (!canView) return <main className="flex flex-1 p-4 md:p-6"><Card className="w-full"><CardHeader><CardTitle>Acceso restringido</CardTitle><CardDescription>No tienes permiso para consultar ventas.</CardDescription></CardHeader></Card></main>
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); setSearch(searchInput.trim()); setPage(1); setSelectedId('') }
  return <main className="flex flex-1 flex-col gap-6 p-4 md:p-6"><section className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-muted-foreground">Finanzas</p><h1 className="text-2xl font-semibold md:text-3xl">Ventas</h1></div>{canManage && <Button onClick={() => { setCreating(true); setSelectedId('') }}>Nueva venta</Button>}</section>
    {creating && canManage && <Card><CardHeader><CardTitle>Crear venta</CardTitle><CardDescription>Los importes finales serán calculados por el backend.</CardDescription></CardHeader><CardContent><SaleForm permissions={permissions} onClose={() => setCreating(false)} onSaved={(sale) => { setCreating(false); setSelectedId(sale.id) }} /></CardContent></Card>}
    {selectedId && <Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>Detalle de venta</CardTitle><Button size="sm" variant="outline" onClick={() => setSelectedId('')}>Cerrar</Button></div></CardHeader><CardContent>{detail.isPending && <p className="text-sm text-muted-foreground">Cargando detalle…</p>}{detail.error && <p role="alert" className="text-sm text-destructive">{saleError(detail.error)}</p>}{detail.data && <SaleDetail sale={detail.data} canManage={canManage} />}</CardContent></Card>}
    <Card><CardHeader className="border-b"><CardTitle>Historial de ventas</CardTitle><CardDescription>Busca por cliente, teléfono o notas y filtra por estado.</CardDescription><form className="flex max-w-3xl flex-col gap-2 pt-2 sm:flex-row" onSubmit={submitSearch}><Input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Buscar ventas" /><select className="h-9 rounded-lg border border-input bg-transparent px-2.5 text-sm" value={status} onChange={(event) => { setStatus(event.target.value as SaleStatus | ''); setPage(1) }}><option value="">Todos los estados</option><option value="DRAFT">Borrador</option><option value="PENDING_PAYMENT">Pendiente de pago</option><option value="PAID">Pagada</option><option value="CANCELLED">Cancelada</option></select><Button type="submit" variant="outline">Buscar</Button></form></CardHeader><CardContent className="space-y-5">{sales.isPending && <p className="text-sm text-muted-foreground">Cargando ventas…</p>}{sales.error && <p role="alert" className="text-sm text-destructive">{saleError(sales.error)}</p>}{sales.data?.items.length === 0 && <p className="text-sm text-muted-foreground">No hay ventas que coincidan.</p>}{sales.data && sales.data.items.length > 0 && <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{sales.data.items.map((sale) => <article key={sale.id} className="flex min-w-0 flex-col gap-3 rounded-lg border p-4"><div className="flex items-start justify-between gap-2"><div><h2 className="font-medium">{sale.customer?.name ?? 'Consumidor final'}</h2><p className="text-sm text-muted-foreground">{new Date(sale.createdAt).toLocaleString()}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs">{statusLabel(sale.status)}</span></div><div className="grid grid-cols-2 gap-2 text-sm"><div><p className="text-xs text-muted-foreground">Total</p><strong>{sale.total}</strong></div><div><p className="text-xs text-muted-foreground">Saldo</p><strong className={sale.balanceDue !== '0.00' ? 'text-amber-700' : 'text-emerald-700'}>{sale.balanceDue}</strong></div></div><Button size="sm" variant="outline" className="mt-auto self-start" onClick={() => { setSelectedId(sale.id); setCreating(false) }}>Ver detalle</Button></article>)}</div>}{sales.data && <div className="flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">{sales.data.total} ventas · Página {page} de {Math.max(sales.data.totalPages, 1)}</p><div className="flex gap-2"><Button variant="outline" disabled={page <= 1 || sales.isFetching} onClick={() => setPage(page - 1)}>Anterior</Button><Button variant="outline" disabled={page >= sales.data.totalPages || sales.isFetching} onClick={() => setPage(page + 1)}>Siguiente</Button></div></div>}</CardContent></Card>
  </main>
}
