import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useSession } from '@/features/auth/use-session'
import { ServiceForm } from '@/features/services/service-form'
import { serviceErrorMessage } from '@/features/services/services-error'
import { useServicesQuery } from '@/features/services/services.queries'
import type { Service } from '@/features/services/services.types'
type Editor = { mode: 'create' } | { mode: 'edit'; service: Service } | null
const PAGE_SIZE = 20
export function ServicesPage() {
  const { data: principal } = useSession(); const permissions = principal?.actorType === 'USER' ? principal.permissions : []; const canView = permissions.includes('services.view'); const canManage = permissions.includes('services.manage'); const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [editor, setEditor] = useState<Editor>(null); const services = useServicesQuery({ search, page, pageSize: PAGE_SIZE }, canView)
  if (!canView) return <main className="flex flex-1 p-4 md:p-6"><Card className="w-full"><CardHeader><CardTitle>Acceso restringido</CardTitle><CardDescription>No tienes permiso para consultar servicios.</CardDescription></CardHeader></Card></main>
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); setSearch(searchInput.trim()); setPage(1); setEditor(null) }; const current = editor?.mode === 'edit' ? editor.service : undefined
  return <main className="flex flex-1 flex-col gap-6 p-4 md:p-6"><section className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-muted-foreground">Catálogo</p><h1 className="text-2xl font-semibold md:text-3xl">Servicios</h1></div>{canManage && <Button onClick={() => setEditor({ mode: 'create' })}>Nuevo servicio</Button>}</section>
    {editor && canManage && <Card><CardHeader><CardTitle>{current ? `Editar ${current.name}` : 'Crear servicio'}</CardTitle><CardDescription>El precio se guarda como decimal exacto.</CardDescription></CardHeader><CardContent><ServiceForm key={current?.id ?? 'new'} service={current} onClose={() => setEditor(null)} onSaved={(saved) => setEditor({ mode: 'edit', service: saved })} /></CardContent></Card>}
    <Card><CardHeader className="border-b"><CardTitle>Catálogo de servicios</CardTitle><CardDescription>Busca por nombre, categoría o descripción.</CardDescription><form className="flex max-w-xl flex-col gap-2 pt-2 sm:flex-row" onSubmit={submitSearch}><Input value={searchInput} onChange={(e) => setSearchInput(e.target.value)} placeholder="Buscar servicios" /><Button type="submit" variant="outline">Buscar</Button></form></CardHeader><CardContent className="space-y-5">{services.isPending && <p className="text-sm text-muted-foreground">Cargando…</p>}{services.error && <p role="alert" className="text-sm text-destructive">{serviceErrorMessage(services.error)}</p>}{services.data?.items.length === 0 && <p className="text-sm text-muted-foreground">{search ? 'No hay coincidencias.' : 'Todavía no hay servicios.'}</p>}
      {services.data && services.data.items.length > 0 && <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{services.data.items.map((service) => <article key={service.id} className="flex min-w-0 flex-col gap-3 rounded-lg border p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate font-medium">{service.name}</h2><p className="text-sm text-muted-foreground">{service.category || 'Sin categoría'}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs">{service.active ? 'Activo' : 'Inactivo'}</span></div><div className="flex justify-between text-sm"><span>{service.durationMinutes} min</span><strong>€ {service.price}</strong></div><p className="line-clamp-2 text-sm text-muted-foreground">{service.description || 'Sin descripción'}</p>{canManage && <Button size="sm" variant="outline" className="mt-auto self-start" onClick={() => setEditor({ mode: 'edit', service })}>Editar</Button>}</article>)}</div>}
      {services.data && <div className="flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">{services.data.total} servicios · Página {page} de {Math.max(services.data.totalPages, 1)}</p><div className="flex gap-2"><Button variant="outline" disabled={page <= 1 || services.isFetching} onClick={() => setPage(page - 1)}>Anterior</Button><Button variant="outline" disabled={page >= services.data.totalPages || services.isFetching} onClick={() => setPage(page + 1)}>Siguiente</Button></div></div>}
    </CardContent></Card>
  </main>
}
